var dataCacheName = 'payback-pwa';
var cacheName = 'payback-pwa-1';
var filesToCache = [
 "./",
 "./index.html",
 "./manifest.json",
 "./service-worker.js",
 //"./audio/",
 "./audio/back.mp3",
 "./audio/congrats.mp3",
 "./audio/burbble.mp3",
 //"./fonts/",
 //"./fonts/roboto/",
 "./fonts/roboto/Roboto-Bold.woff",
 "./fonts/roboto/Roboto-Bold.woff2",
 "./fonts/roboto/Roboto-Light.woff",
 "./fonts/roboto/Roboto-Light.woff2",
 "./fonts/roboto/Roboto-Medium.woff",
 "./fonts/roboto/Roboto-Medium.woff2",
 "./fonts/roboto/Roboto-Regular.woff",
 "./fonts/roboto/Roboto-Regular.woff2",
 "./fonts/roboto/Roboto-Thin.woff",
 "./fonts/roboto/Roboto-Thin.woff2",
 "./fonts/PAYBACK_Regular.ttf",
 //"./images/",
 //"./images/icons/",
 "./images/icons/icon-128x128.png",
 "./images/icons/icon-144x144.png",
 "./images/icons/icon-152x152.png",
 "./images/icons/icon-192x192.png",
 "./images/icons/icon-256x256.png",
 "./images/explosion-azul.png",
 "./images/explosion-roja.png",
 "./images/burble-left.png",
 "./images/burble-right.png",
 "./images/button.png",
 "./images/button-next.png",
 "./images/fondoIntro.png",
 "./images/fondoPlay2.png",
 "./images/logo-amex.png",
 "./images/logo-payback.png",
 "./images/pointee1-left-talk.png",
 "./images/pointee1-right-talk.png",
 "./images/pointee2-left-talk.png",
 "./images/pointee2-right-talk.png",
 "./images/fondoPlay2.png",
 "./images/fondoPlay2.png",
 "./images/fondoPlay2.png",
 //"./images/animaciones/",
 //"./images/animaciones/MARK/",
 "./images/animaciones/MARK/ADIDAS/left.gif",
 "./images/animaciones/MARK/ADIDAS/right.gif",
 "./images/animaciones/MARK/AMERICANEXPRESS/left.gif",
 "./images/animaciones/MARK/AMERICANEXPRESS/right.gif",
 "./images/animaciones/MARK/APPLE/left.gif",
 "./images/animaciones/MARK/APPLE/right.gif",
 "./images/animaciones/MARK/ARRACHERAHOUSE/left.gif",
 "./images/animaciones/MARK/ARRACHERAHOUSE/right.gif",
 "./images/animaciones/MARK/BESTBUY/left.gif",
 "./images/animaciones/MARK/BESTBUY/right.gif",
 "./images/animaciones/MARK/BOOKINGCOM/left.gif",
 "./images/animaciones/MARK/BOOKINGCOM/right.gif",
 "./images/animaciones/MARK/CAFEDILETTO/left.gif",
 "./images/animaciones/MARK/CAFEDILETTO/right.gif",
 "./images/animaciones/MARK/CINEMEX/left.gif",
 "./images/animaciones/MARK/CINEMEX/right.gif",
 "./images/animaciones/MARK/ELFAROLITO/left.gif",
 "./images/animaciones/MARK/ELFAROLITO/right.gif",
 "./images/animaciones/MARK/ELSURTIDOR/left.gif",
 "./images/animaciones/MARK/ELSURTIDOR/right.gif",
 "./images/animaciones/MARK/GIORNALE/left.gif",
 "./images/animaciones/MARK/GIORNALE/right.gif",
 "./images/animaciones/MARK/HERTZ/left.gif",
 "./images/animaciones/MARK/HERTZ/right.gif",
 "./images/animaciones/MARK/HOTELESMISION/left.gif",
 "./images/animaciones/MARK/HOTELESMISION/right.gif",
 "./images/animaciones/MARK/INTERJET/left.gif",
 "./images/animaciones/MARK/INTERJET/right.gif",
 "./images/animaciones/MARK/JUGUETRON/left.gif",
 "./images/animaciones/MARK/JUGUETRON/right.gif",
 "./images/animaciones/MARK/KRISPYKREME/left.gif",
 "./images/animaciones/MARK/KRISPYKREME/right.gif",
 "./images/animaciones/MARK/LACOMER/left.gif",
 "./images/animaciones/MARK/LACOMER/right.gif",
 "./images/animaciones/MARK/MEGASORIANA/left.gif",
 "./images/animaciones/MARK/MEGASORIANA/right.gif",
 "./images/animaciones/MARK/MODATELAS/left.gif",
 "./images/animaciones/MARK/MODATELAS/right.gif",
 "./images/animaciones/MARK/NETSHOES/left.gif",
 "./images/animaciones/MARK/NETSHOES/right.gif",
 "./images/animaciones/MARK/NEVEGELATO/left.gif",
 "./images/animaciones/MARK/NEVEGELATO/right.gif",
 "./images/animaciones/MARK/NUNYSYOGURT/left.gif",
 "./images/animaciones/MARK/NUNYSYOGURT/right.gif",
 "./images/animaciones/MARK/OSOM/left.gif",
 "./images/animaciones/MARK/OSOM/right.gif",
 "./images/animaciones/MARK/PETROSEVEN/left.gif",
 "./images/animaciones/MARK/PETROSEVEN/right.gif",
 "./images/animaciones/MARK/SANTANDER/left.gif",
 "./images/animaciones/MARK/SANTANDER/right.gif",
 "./images/animaciones/MARK/SBARRO/left.gif",
 "./images/animaciones/MARK/SBARRO/right.gif",
 "./images/animaciones/MARK/SEVENELEVEN/left.gif",
 "./images/animaciones/MARK/SEVENELEVEN/right.gif",
 "./images/animaciones/MARK/SIXTIESBURGUER/left.gif",
 "./images/animaciones/MARK/SIXTIESBURGUER/right.gif",
 "./images/animaciones/MARK/SORTEOSTEC/left.gif",
 "./images/animaciones/MARK/SORTEOSTEC/right.gif",
 "./images/animaciones/MARK/SUSHIITTO/left.gif",
 "./images/animaciones/MARK/SUSHIITTO/right.gif",
 "./images/animaciones/MARK/TACOINN/left.gif",
 "./images/animaciones/MARK/TACOINN/right.gif",
 "./images/animaciones/MARK/TRAVELIMPRESSIONS/left.gif",
 "./images/animaciones/MARK/TRAVELIMPRESSIONS/right.gif",
 "./images/animaciones/MARK/UNDOSTRES/left.gif",
 "./images/animaciones/MARK/UNDOSTRES/right.gif",
 //"./images/animaciones/AMEX/",
 "./images/animaciones/AMEX/ADIDAS/left.gif",
 "./images/animaciones/AMEX/ADIDAS/right.gif",
 "./images/animaciones/AMEX/APPLE/left.gif",
 "./images/animaciones/AMEX/APPLE/right.gif",
 "./images/animaciones/AMEX/ARRACHERAHOUSE/left.gif",
 "./images/animaciones/AMEX/ARRACHERAHOUSE/right.gif",
 "./images/animaciones/AMEX/BESTBUY/left.gif",
 "./images/animaciones/AMEX/BESTBUY/right.gif",
 "./images/animaciones/AMEX/BOOKINGCOM/left.gif",
 "./images/animaciones/AMEX/BOOKINGCOM/right.gif",
 "./images/animaciones/AMEX/CAFEDILETTO/left.gif",
 "./images/animaciones/AMEX/CAFEDILETTO/right.gif",
 "./images/animaciones/AMEX/CINEMEX/left.gif",
 "./images/animaciones/AMEX/CINEMEX/right.gif",
 "./images/animaciones/AMEX/ELFAROLITO/left.gif",
 "./images/animaciones/AMEX/ELFAROLITO/right.gif",
 "./images/animaciones/AMEX/ELSURTIDOR/left.gif",
 "./images/animaciones/AMEX/ELSURTIDOR/right.gif",
 "./images/animaciones/AMEX/GIORNALE/left.gif",
 "./images/animaciones/AMEX/GIORNALE/right.gif",
 "./images/animaciones/AMEX/HERTZ/left.gif",
 "./images/animaciones/AMEX/HERTZ/right.gif",
 "./images/animaciones/AMEX/HOTELESMISION/left.gif",
 "./images/animaciones/AMEX/HOTELESMISION/right.gif",
 "./images/animaciones/AMEX/INTERJET/left.gif",
 "./images/animaciones/AMEX/INTERJET/right.gif",
 "./images/animaciones/AMEX/JUGUETRON/left.gif",
 "./images/animaciones/AMEX/JUGUETRON/right.gif",
 "./images/animaciones/AMEX/KRISPYKREME/left.gif",
 "./images/animaciones/AMEX/KRISPYKREME/right.gif",
 "./images/animaciones/AMEX/LACOMER/left.gif",
 "./images/animaciones/AMEX/LACOMER/right.gif",
 "./images/animaciones/AMEX/MEGASORIANA/left.gif",
 "./images/animaciones/AMEX/MEGASORIANA/right.gif",
 "./images/animaciones/AMEX/MODATELAS/left.gif",
 "./images/animaciones/AMEX/MODATELAS/right.gif",
 "./images/animaciones/AMEX/NETSHOES/left.gif",
 "./images/animaciones/AMEX/NETSHOES/right.gif",
 "./images/animaciones/AMEX/NEVEGELATO/left.gif",
 "./images/animaciones/AMEX/NEVEGELATO/right.gif",
 "./images/animaciones/AMEX/NUNYSYOGURT/left.gif",
 "./images/animaciones/AMEX/NUNYSYOGURT/right.gif",
 "./images/animaciones/AMEX/OSOM/left.gif",
 "./images/animaciones/AMEX/OSOM/right.gif",
 "./images/animaciones/AMEX/PETROSEVEN/left.gif",
 "./images/animaciones/AMEX/PETROSEVEN/right.gif",
 "./images/animaciones/AMEX/SANTANDER/left.gif",
 "./images/animaciones/AMEX/SANTANDER/right.gif",
 "./images/animaciones/AMEX/SBARRO/left.gif",
 "./images/animaciones/AMEX/SBARRO/right.gif",
 "./images/animaciones/AMEX/SEVENELEVEN/left.gif",
 "./images/animaciones/AMEX/SEVENELEVEN/right.gif",
 "./images/animaciones/AMEX/SIXTIESBURGUER/left.gif",
 "./images/animaciones/AMEX/SIXTIESBURGUER/right.gif",
 "./images/animaciones/AMEX/SORTEOSTEC/left.gif",
 "./images/animaciones/AMEX/SORTEOSTEC/right.gif",
 "./images/animaciones/AMEX/SUSHIITTO/left.gif",
 "./images/animaciones/AMEX/SUSHIITTO/right.gif",
 "./images/animaciones/AMEX/TACOINN/left.gif",
 "./images/animaciones/AMEX/TACOINN/right.gif",
 "./images/animaciones/AMEX/TRAVELIMPRESSIONS/left.gif",
 "./images/animaciones/AMEX/TRAVELIMPRESSIONS/right.gif",
 "./images/animaciones/AMEX/UNDOSTRES/left.gif",
 "./images/animaciones/AMEX/UNDOSTRES/right.gif",
 //"./scripts/",
 "./scripts/app.js",
 "./scripts/jquery-3.3.1.js",
 "./scripts/materialize.js",
 //"./scripts/materialize.min.js",
 //"./styles/",
 "./styles/materialize.css",
 "./styles/material-icon.css",
 "./styles/style.css"
];

self.addEventListener('install', function(e) {
  console.log('[ServiceWorker] Install');
  e.waitUntil(
    caches.open(cacheName).then(function(cache) {
      console.log('[ServiceWorker] Caching app shell');
      return cache.addAll(filesToCache);
    })
  );
});

self.addEventListener('activate', function(e) {
  console.log('[ServiceWorker] Activate');
  e.waitUntil(
    caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        if (key !== cacheName && key !== dataCacheName) {
          console.log('[ServiceWorker] Removing old cache', key);
          return caches.delete(key);
        }
      }));
    })
  );
  return self.clients.claim();
});

self.addEventListener('fetch', function(e) {
  console.log('[Service Worker] Fetch', e.request.url);
  e.respondWith(
    caches.match(e.request).then(function(response) {
      return response || fetch(e.request);
    })
  );
});
